### ISSUE TITLE
daf cli sdr should give option to set `iss` on request claim(s)

### ISSUE THREAD

**Issue by rado0x54** [uport-project/daf#101]
Currently the cli for `sdr` does not expose to the the `iss` field on the items of the `claims` array:

```
? Claim type name
? Reason We need this to comply with local law
? Is essential Yes
```

CLI should expose all capabilities of the SDR.

**Comment by rado0x54** [comment]
@simonas-notcat i may do this myself. ticket is mainly for keeping track of it.

**Comment by simonas-notcat** [comment]
Fixed in https://github.com/uport-project/daf/releases/tag/v2.5.0

**Comment by rado0x54** [comment]
Awesome, thanks!
