### ISSUE TITLE
Fetch raw message from URL

### ISSUE THREAD

**Issue by simonas-notcat** [uport-project/daf#103]
## Problem:

When using QR Code flow, it is sometimes impossible to fit all information into a QRCode. 

## Solution:

It should be possible to scan a QR Code that contains a URL that is pointing to a message. Something like this:

```
https://example-service.io/presentation/1234567
```

**Comment by mirceanis** [comment]
probably a good idea to include `/ipfs/<hash>` as a possible pointer to a message

**Comment by simonas-notcat** [comment]
> probably a good idea to include `/ipfs/<message hash>` as a possible pointer to a message

@mirceanis let's add it as a separate feature in the future
