### ISSUE TITLE
SQLITE_CONSTRAINT: FOREIGN KEY constraint failed

### ISSUE THREAD

**Issue by devrajsinghrawat** [uport-project/daf#110]
I am trying to use DFA CLI 

Performed steps mentioned in https://github.com/uport-project/daf#getting-started

But when I was done with 

yarn install,
yarn bootstrap and yarn build

I had tried to create an Identity using  

npx daf identity-manager --create

and I have received an error 

SQLITE_CONSTRAINT: FOREIGN KEY constraint failed

![Screenshot 2020-03-26 at 09 01 25](https://user-images.githubusercontent.com/44597990/77623458-6c130f80-6f40-11ea-8dd5-fcdcc3cd35df.png)

Node version - v10.19.0
OS: Mac

**Comment by simonas-notcat** [comment]
@devrajsinghrawat can you try to clear your identity store. I suspect that the DB schema has changed.

```
rm -rf ~/.daf
```

**Comment by devrajsinghrawat** [comment]
It does work !
