### ISSUE TITLE
KMS: encrypt private keys

### ISSUE THREAD

**Issue by simonas-notcat** [uport-project/daf#123]
`KeyManagementSystem` should take an encryption key as a constructor param, and then use it to encrypt/decrypt private keys that are stored by the KeyStore

**Comment by simonas-notcat** [comment]
It makes more sense to do this encryption in KeyStore, and not in the KMS

**Comment by mirceanis** [comment]
> It makes more sense to do this encryption in KeyStore, and not in the KMS

:) I was about to comment this when you first posted the issue but see that you already did it in the implementation
