### ISSUE TITLE
Question: How to add extra information in 'PresentationJwt'

### ISSUE THREAD

**Issue by amarts** [uport-project/daf#166]
As a response to SDR, we sent VP.

In daf-w3c, the PresentationJwt  (https://github.com/uport-project/daf/blob/d82de5495f89ea220c3c981c3702d5861b8f0fba/packages/daf-w3c/src/graphql.ts#L67) has a prescribed list of fields allowed.

I wanted to understand, is there a provision for adding metaData to the SIGN_VP payload.

Usecase:

One of my employee needs to visit multiple client location, I want him to scan a QR (SDR jwt) in client location as proof of visit. But to double check he is not scanning it from other locations I want to capture the location of the scan too! As location (lat/lng) is a dynamic info, we would have an VC for this, so would like to see if I send it as metaData as response!

**Comment by mirceanis** [comment]
if you create a VC for lat/long, you can include that VC in a presentation.
It would be one of the credentials in the `SignPresentationInput.verifiableCredential` array

**Comment by devrajsinghrawat** [comment]
Hi @amarts ,

If I understand your question properly then you can indeed add additional information in your VP .

Just to to add that information with the key which is not the reserved one .. .i.e. the reserved one u can find in the below code .. This is used in transformPresentationInput inside action handler 


```
const transformPresentationInput = (input: PresentationInput): PresentationPayload => {
  const result = { vp: {} }

  for (const key in input) {
    switch (key) {
      case '@context':
      case 'context':
        result['vp']['@context'] = input[key]
        break
      case 'type':
        result['vp']['type'] = input[key]
        break
      case 'issuanceDate':
        result['nbf'] = Date.parse(input[key]) / 1000
        break
      case 'expirationDate':
        result['exp'] = Date.parse(input[key]) / 1000
        break
      case 'id':
        result['jti'] = input[key]
        break
      case 'audience':
        result['aud'] = input[key]
        break
      case 'verifiableCredential':
        result['vp']['verifiableCredential'] = input[key]
        break
      case 'issuer':
        // remove issuer
        break
      default:
        result[key] = input[key]
    }
  }

  return result as PresentationPayload
}

```

So in more simple way .. try to add those additional information in your payload data before signing the Persentation 

```
const actionSignVp = async (
    did: string,
    data: VerifiablePresentationInput
) => {
    const payload = {
        issuer: did,
        audience: [data.aud],
        '@context': ['https://www.w3.org/2018/credentials/v1'],
        type: ['VerifiablePresentation'],
        verifiableCredential: data.vp.verifiableCredential,
    }

    if (data.lat) payload['lat'] = data.lat
    if (data.Ing) payload['Ing'] = data.Ing

    const vpJwt = await agent.handleAction({
        type: W3c.ActionTypes.signPresentationJwt,
        data: payload,
        save: true,
    } as W3c.ActionSignW3cVp)

    return vpJwt;
}

```
