### ISSUE TITLE
Error: Unable to resolve module `path` from `node_modules/libsodium/dist/modules/libsodium.js`

### ISSUE THREAD

**Issue by devrajsinghrawat** [uport-project/daf#179]
Hi Team,

I have come across below error when, I had upgraded to DAF5 

bundling failed: Error: Unable to resolve module `path` from `node_modules/libsodium/dist/modules/libsodium.js`: path could not be found within the project.

I had used the guideline https://github.com/uport-project/daf/blob/master/docs/Docs.md which was primarily for DAF 4 upgrade, where we are using DAF-libsodium But when I had compared the same in daf-mobile implementation, then it was daf-react-native-libsodium instead of daf-libsodium  

https://github.com/uport-project/daf-mobile/blob/master/src/lib/setup.ts#L5  

So should we use daf-react-native-libsodium instead of daf-libsodium for keyManagement?

**Comment by jasonhealy** [comment]
Yes, For react native use `daf-react-native-libsodium` for Node use `daf-libsodium`

**Comment by devrajsinghrawat** [comment]
Hi @jasonhealy Thanks for your input , Issue had resolved after updating to daf-react-native-libsodium from daf-libsodium (for react Native)
