### ISSUE TITLE
The latest version (`6.1.0`) is not available on NPM

### ISSUE THREAD

**Issue by Muhammad-Altabba** [uport-project/daf#180]
DAF has v6.1.0 (https://github.com/uport-project/daf/releases/tag/v6.1.0)

But the latest version available at https://www.npmjs.com/package/daf-core is 6.0.0. Which is 2 versions old (there is 6.0.1 and 6.1.0 after it)

**Comment by jasonhealy** [comment]
The release commit shows which packages get bumped: https://github.com/uport-project/daf/commit/48ad05158225e3020f3a1a937b3d4a0a78841edb

**Comment by Muhammad-Altabba** [comment]
Ok, Thanks, I thought all the versions are bumped together.
