### ISSUE TITLE
RepositoryNotFoundError: No repository for "Claim" was found.

### ISSUE THREAD

**Issue by devrajsinghrawat** [uport-project/daf#182]
Dear team,

I am getting this error while upgrade to DAF 5

RepositoryNotFoundError: No repository for "Claim" was found. Looks like this entity is not registered in current "default" connection?

Please suggest if this is a known issue.

**Comment by devrajsinghrawat** [comment]
This is the setup file for DAF 5 upgrade 

```
// 1- Setting up the database connection
import { Entities } from 'daf-core'
import { createConnection, getConnection, Connection } from 'typeorm'
// https://typeorm.io/#/connection-options

import { IdentityProvider } from 'daf-ethr-did'
import { KeyStore } from 'daf-core'
import { KeyManagementSystem } from 'daf-react-native-libsodium'
import { IdentityStore } from 'daf-core'
import { DafResolver } from 'daf-resolver'
import { UrlMessageHandler } from 'daf-url'
import { DIDCommMessageHandler } from 'daf-did-comm'
import { JwtMessageHandler } from 'daf-did-jwt'
import { W3cMessageHandler } from 'daf-w3c'
import { SdrMessageHandler } from 'daf-selective-disclosure'
import { W3cActionHandler } from 'daf-w3c'
import { DIDCommActionHandler } from 'daf-did-comm'
import { SdrActionHandler } from 'daf-selective-disclosure'
import { Agent } from 'daf-core'
import { DataStore } from 'daf-data-store'

import { IdentityContext } from './IdentityContext';

const dbConnection = createConnection({
  type: 'react-native',
  database: 'daf.sqlite',
  location: 'default',
  synchronize: true,
  logging: ['error'],
  entities: [...Entities],
});

dbConnection.then( () => {
  console.log('DB Connection has been initialized!!!')
})

// 2 - We will be using 'did:ethr' identities

// 3 - Storing key pairs in the database
const keyStore = new KeyStore(dbConnection)

// 4 - KeyManagementSystem is responsible for managing encryption and signing keys
const kms = new KeyManagementSystem(keyStore)

// 5 - Storing managed identities in the database
export const identityStore = new IdentityStore('rinkeby', dbConnection)

// Infura is being used to access Ethereum blockchain. https://infura.io
const infuraProjectId = '5ffc47f65c4042ce847ef66a3fa70d4c'

// Injecting required dependencies, and specifying which blockchain to use and how to access it
const rinkebyIdentityProvider = new IdentityProvider({
  kms,
  identityStore,
  network: 'rinkeby',
  rpcUrl: 'https://rinkeby.infura.io/v3/' + infuraProjectId,
})

// Using local DID Document resolver. It is being used internally to validate messages and to get information about service endpoints
const didResolver = new DafResolver({ infuraProjectId })

// Setting up Message Handler Chain
const messageHandler = new UrlMessageHandler()
messageHandler
  .setNext(new DIDCommMessageHandler())
  .setNext(new JwtMessageHandler())
  .setNext(new W3cMessageHandler())
  .setNext(new SdrMessageHandler())

// Setting up Action Handler Chain
const actionHandler = new W3cActionHandler()
actionHandler
  .setNext(new SdrActionHandler())
  .setNext(new DIDCommActionHandler())

// Initializing the Core
export const core = new Agent({
  dbConnection,
  didResolver,
  identityProviders: [rinkebyIdentityProvider],
  actionHandler,
  messageHandler,
})

export const dataStore = new DataStore()

core.identityManager.getIdentities().then(identities => {
  console.log('identities', identities);
})

export const initializeDB = async () => {
  console.log('1 - Inside initializeDB function ')
  IdentityContext.Initialize();
  return await Promise.resolve(dbConnection);
}


```


This is the section of code where Entities are being registered 

```
const dbConnection = createConnection({
  type: 'react-native',
  database: 'daf.sqlite',
  location: 'default',
  synchronize: true,
  logging: ['error'],
  entities: [...Entities],              <----------- 
});


```

and when I checked on these entities and can see that Claim are part of the array

**Comment by jasonhealy** [comment]
There were breaking changes to the data model in this upgrade so you will need to delete the app and reinstall to wipe the existing db

**Comment by devrajsinghrawat** [comment]
Hi @jasonhealy thanks for your response ..

I think this issue is not because of reinstall as I had already did that part many time ,, 

More over I have come across on a conclusion which you might suggest is the correct way of doing it.

1-  I was getting the same error ** RepositoryNotFoundError: No repository for "Claim" was found. Looks like this entity is not registered in current "default" connection?** when I was trying to fetch the claims using 

```
import { DataStore } from 'daf-data-store'
const dataStore = new DataStore()
await dataStore.findCredentialsByFields({
             sub: [this.userIdentity?.did],
            claim_type: name
         }))
```

But when I change the code in the below manner then the error had disappeared

```
        const dbConnection = await agent.dbConnection
        return (await dbConnection.getRepository('Claim').find({
            where: {
              subject: this.userIdentity?.did,
              type: 'name',
            },
            relations: ['credential'],
          }))
``` 

Please do suggest if you have any comment on above approach

**Comment by devrajsinghrawat** [comment]
So the question comes .. If some times I need to directly interact with dataStore like to get dataStore.popularClaimForDid(did, 'name');

in that case it always complains for RepositoryNotFoundError even though that repo can be retrieved using dbConnection 

```
  name: 'RepositoryNotFoundError',
  message:
   'No repository for "Claim" was found. Looks like this entity is not registered in current "default" connection?' }

```

**Comment by devrajsinghrawat** [comment]
I hope this is not because 

"daf-data-store": {
      "version": "3.4.2",
which has dependency on         "daf-core": "^3.4.2",

Please check the screenshot below!

![Screenshot 2020-06-05 at 19 50 00](https://user-images.githubusercontent.com/44597990/83907521-d678d500-a765-11ea-832e-292d37eaa1e9.png)

**Comment by devrajsinghrawat** [comment]
So when I am using 

dataStore.popularClaimForDid(identity.did, 'name'); It throws the exception But when I copies the same code which is written inside popularClaimForDID using 

await dbConnection.getRepository(Claim)

then it works .. But it does not make any sense to copy the code from existing Lib which is exposing it using functions ..

So I believe there should be some config missing which can have the dataStore to be work properly.. What do you suggest @jasonhealy

**Comment by jasonhealy** [comment]
I think I see your issue - `daf-data-store` is deprecated and should not be used in daf5. See examples here directly accessing Claim from `daf-core` -  https://github.com/uport-project/dafhub/blob/master/pages/api/user.ts

**Comment by devrajsinghrawat** [comment]
@jasonhealy Thanks for your reply .. Oh I see .. 

So would you recommend stored entities data using daf-core or 
using dbConnection.getRepository(<entity-name>)

**Comment by jasonhealy** [comment]
Both ways are the same so it's up to you to choose which pattern works best for your app. Right now we just expose TypeORM functionality. In coming releases we plan to have a better abstraction layer for storage so `daf` will be decoupled from TypeORM allowing you to use other storage apis.

**Comment by devrajsinghrawat** [comment]
Thanks for your inputs .. Closing the issue

**Comment by devrajsinghrawat** [comment]
Hi @jasonhealy I was wondering as daf-data-store is deprecated

In which Module the relevant functions like 

- shortId
- credentialsForMessageId
- credentialsFieldsForClaimHash
- findMessagesByVC
- popularClaimForDid

etc

**Comment by jasonhealy** [comment]
These abstractions have been removed from core as they are mostly client specific. You can create these convenience methods directly in your app as they would be just simple wrappers around TypeORM queries.

**Comment by devrajsinghrawat** [comment]
Oh Ok Thanks ....
