### ISSUE TITLE
DAF 5 - No Credential related Message were being saved during Self singed Claim

### ISSUE THREAD

**Issue by devrajsinghrawat** [uport-project/daf#196]
Hi Team,

I was using the below code for signing and saving the claims and it was storing data in Credential table but not in Message table 

```
    async signVc(claimType: string, claimValue: string) {
        let credentialSubject: object = {}
        credentialSubject[claimType] = claimValue
        credentialSubject['id'] = this.userIdentity?.did

        const vcJwt: Daf.Credential = await agent.handleAction({
            type: W3cActionTypes.signCredentialJwt,
            save: true,
            data: {
                '@context': ['https://www.w3.org/2018/credentials/v1'],
                type: ['VerifiableCredential'],
                issuer: this.userIdentity?.did,
                credentialSubject: credentialSubject
            }
        } as ActionSignW3cVc)

```

Then I need to write further code as mentioned below to store data for self sign claims in table

```

        const sdrMessage: Daf.Message = await agent.handleMessage({
            raw: vcJwt.raw,
            save: true, // default = true
          })
```

Now I am not sure if there is a Bug in agent.handleAction Or it is a must to use agent.handleMessage to save data in Message table?

**Comment by simonas-notcat** [comment]
That is the expected behaviour. 

Credential !== Message

You don't have to query Message table to get the list of credentials. Just query Credentials table.

**Comment by devrajsinghrawat** [comment]
@simonas-notcat Yes I agree Credential !== Message

But Message does have a type called w3c.vc, sdr or other as well so that mean the table should record all the actions happening in the application and When we try to query Message table then we don't find the records of Self Signed Claims creation as they dont get inserted until we use the below additional logic

```
  const sdrMessage: Daf.Message = await agent.handleMessage({
            raw: vcJwt.raw,
            save: true, // default = true
          })

``


![Screenshot 2020-06-10 at 09 59 06](https://user-images.githubusercontent.com/44597990/84242412-1abafb00-ab01-11ea-9578-39cf46e8b8dd.png)


`

So Do you think, everything should be added to message table as well as a Log else we need to query each tables separately to fetch the history .. What do u suggest
