### ISSUE TITLE
Multiple end point support

### ISSUE THREAD

**Issue by devrajsinghrawat** [uport-project/daf#201]
Hi Team,

Does DAF 5 support multiple service end point support or if I had registered a service end point by mistake then what all the option for me to correct it?

**Comment by devrajsinghrawat** [comment]
Hi Team, 

Did I miss anything in my above issue to provide?

**Comment by mirceanis** [comment]
You did not miss anything.
I think the current functionality is to pick the first matching endpoint from the DID document.
The same is generally true when using keys from the DID document.
This is not meant to be a complete solution, but an MVP.
Feel free to propose a better solution if one is at hand.

Please reopen if this is still an issue.

**Comment by devrajsinghrawat** [comment]
2+5
....-
0





++++++++++++++++++
-.
300112
