### ISSUE TITLE
No signing key after `handleMessage` (Daf7)

### ISSUE THREAD

**Issue by jasonhealy** [uport-project/daf#206]
Using the rest API `daf-rest` daf cannot sign credentials/presentations after it stores an SDR message.

Error message: `daf:w3c:action-handler Error: No signing key`

**To recreate:** 

1. Create new identity in clean db
2. Sign a credential: ~ `/agent/createVerifiableCredential `
3. Create an SDR message (in a separate daf instance) and handleMessage ~`agent/handleMessage`
4. Sign a credential or (presentation) again ~`Error: No signing key``

**Comment by simonas-notcat** [comment]
Fixed in https://github.com/uport-project/daf/commit/df40d7e12750b7016c693f1a3f86c83bda4a0e89
