### ISSUE TITLE
update documents

### ISSUE THREAD

**Issue by ilovelili** [uport-project/daf#211]
Could you please update the documents since some of them seem to be obsolete.

For example: [`https://github.com/uport-project/daf/blob/master/docs/MessageValidator.md`](https://github.com/uport-project/daf/blob/master/docs/MessageValidator.md)

While `MessageValidator` seems to be redefined to `MessageHandler` so it's somehow misleading.

Thank you very much!

**Comment by rado0x54** [comment]
This should be handled in #47.

**Comment by rado0x54** [comment]
Moved to #47
