### ISSUE TITLE
Agent not working on React Native

### ISSUE THREAD

**Issue by ilanolkies** [uport-project/daf#221]
Hi! RIF team is now working on verifiable credential implementations, trying to use DAF agent in React Native. For some reason our setup seems to be wrong (or there's a bug).

I created a mini project reproducing the error cought in RIF apps

Repo: https://github.com/rsksmart/rif-identity-daf-mini
Setup agent: https://github.com/rsksmart/rif-identity-daf-mini/blob/master/setup.js
Using agent: https://github.com/rsksmart/rif-identity-daf-mini/blob/master/App.js

When the app runs `createIdentity` the database transaction for creating the key is committed but the db transaction for creating the identity is reverted. This behaviour can be reproduced by running the app and clicking on `Create` button. It just triggers:

```ts
const identity = await agent.identityManager.createIdentity()
```

Thanks,

**Comment by jasonhealy** [comment]
@ilanolkies - Can you try fixing your version of typeORM to 0.2.24 to rule that out? There have been reported issues with 0.2.25.

**Comment by ilanolkies** [comment]
@jasonhealy - it's working now! Thanks!!
