### ISSUE TITLE
Example React App is not sending credentials to trust graph

### ISSUE THREAD

**Issue by HamzaBinSarfraz** [uport-project/daf#222]
[react-app](https://github.com/uport-project/daf/tree/master/examples/react-app) is not sending credentials to [trust-graph](https://trustgraph.uport.me/graphql), here is the screenshot that from network returning 400
![Screenshot from 2020-08-20 12-02-43](https://user-images.githubusercontent.com/30901435/90728092-ba54f080-e2dd-11ea-84d7-dc6bd5e19016.png)

and here is the screenshot of findEdge in graphql interface

![Screenshot from 2020-08-20 12-04-21](https://user-images.githubusercontent.com/30901435/90728170-dc4e7300-e2dd-11ea-9f33-97e9db9ebfe3.png)

**Comment by mirceanis** [comment]
I'm afraid this feature will be deprecated and I'm not sure if there's a direct replacement.
Trust-graph is no longer receiving support so the DAF module that was using it will probably be removed in the next major version.

**Comment by HamzaBinSarfraz** [comment]
Alright Thanks
