### ISSUE TITLE
How can we generate a SDR on-behalf of issuer

### ISSUE THREAD

**Issue by devrajsinghrawat** [uport-project/daf#238]
Hi Team,

While handling a scenario, where user is scanning a QR code which is seeking attestation from a issuer but as user does not have attestations yet from that issuer and could not able to share the credentials.

But by this time, We already have information about 
1) Requested Attester DID
2) Claim type which were requested 

So based on that data, I was trying to generate a SDR on-behalf of issuer and directly sharing the self signed credentials against the generated SDR to Issuer for attestation instead of asking user to go to attester/issuer portal and scan the QR code.

But while generating the SDR on behalf I'm getting a error 

Error: the string "No identity: did:ethr:rinkeby:0xe000315b4fd38b0291c0b65c69b86f805fdab09e" was thrown

did:ethr:rinkeby:0xe000315b4fd38b0291c0b65c69b86f805fdab09e is the DID of issuer which was captured from the SP SDR.

code block used 
```
  const jwt = await agent.handleAction({
    type: SD.ActionTypes.signSdr,
    did: signerDid,
    data: sdrInput,
    save: true,
  } as SD.ActionSignSdr);
```

Could you kindly suggest if there is a way to Generate SDR on behalf

**Comment by jasonhealy** [comment]
If I understand your question correctly you are trying to respond to an SDR request at a later stage? 

This is very straight forward. When you receive the request ensure the message is saved to the db so you can query for it later and then respond with the VCs. When saved the request will save as a message of type `sdr`.

**Comment by devrajsinghrawat** [comment]
Hi @jasonhealy .. Yes I agree what you said and I believe the feature was used in DAF-Mobile where we could check  the activity log and respond to a SDR ..

But here the scenario is different 

Here we can not respond to scanned service provider's SDR until we get the attested credentials from issuer (which is embedded into Service providers SDR) so here I am trying to generated a SDR for user so that by using  that SDR he can approve and share his Self Signed Claims to the Issuer's service endpoint ( FYI i am capturing the issuer from the Service provider SDR) ..

Both SDR are different  in our Case.. Once User will receive attested credentials then what you have said can be done.. (i.e. respond to an SDR which was scanned initially)

**Comment by jasonhealy** [comment]
So you cannot do something like this? -
1) Scan service provider's selective disclosure request and save to db
2) Receive or create credentials and save
3) Query for SDR in step 1 and send credentials from step 2

It's not possible to sign on behalf of another identity (it defeats the purpose of signing). You can also just create a VP and send it to where ever you want (service providers endpoint for example)

**Comment by devrajsinghrawat** [comment]
So to Draw a conclusion from above

 - When any one is creating a SDR that time requestor signs using his keys 
 - We can create a VP and Share it with a DID (requestor) without a SDR request

**Comment by jasonhealy** [comment]
Correct. When you respond to an SDR all you are doing is creating a VP and sending it to an endpoint specified in the request or in the DID document.

**Comment by devrajsinghrawat** [comment]
Thanks @jasonhealy for the support ..

let me try and check how I can create a VP without a SDR ...

**Comment by devrajsinghrawat** [comment]
Hi @jasonhealy 

**"When you respond to an SDR all you are doing is creating a VP"**  

Just reopened to clarify that we can create a VP without a SDR as well..

**Comment by jasonhealy** [comment]
Yes, Both VP and SDR are message types and can be created independently and sent anywhere. You can create arbitrary VP messages for example as a QR code so anyone can scan it.

You can however optionally provide a `threadId` in your SDR so when you send the VP response you can pass that id along so your database can tie responses to requests.

**Comment by devrajsinghrawat** [comment]
many thanks @jasonhealy for the prompt support
