### ISSUE TITLE
usage for signCredentialJwt vs signPresentationJwt

### ISSUE THREAD

**Issue by devrajsinghrawat** [uport-project/daf#243]
Dear Team,

Hope you are doing great. I have a question on VC sign and VP Sign used in DAF .. I would like to confirm my understand on  case 1 and case 2

**Case 1)** 
const jwt = await agent.handleAction({
            type: W3c.ActionTypes.signCredentialJwt,
........
    } as W3c.ActionSignW3cVc)

**Case 2)** 
    const vpJwt = await agent.handleAction({
        type: W3c.ActionTypes.signPresentationJwt,
        data: payload,
        save: true,
    } as W3c.ActionSignW3cVp)

I was using using case 1 (vc sign) for self signed credentials creation and case 2 (vp sign) when I need to share **ONE** or  multiple credentials;

Scenario: Issuer is creating a QR for information about himself, which others can scan and get details about him using this QR code. For that purpose 

Q: is it suggest-able to use VC-sign for creating and then sharing (as QR code) the credentials without wrapping them into a VP?

**Comment by mirceanis** [comment]
Yes, that would certainly work as long as there is a single VC.
Perhaps it would work even better than a VP since the QR-code would be smaller.

When you need to share multiple VCs, then it's best to stick to a a VP.
