### ISSUE TITLE
Cross Chain compatibility 

### ISSUE THREAD

**Issue by devrajsinghrawat** [uport-project/daf#244]
Dear Team,

In the below scenario..

1) User:  is using an application which is based on DAF
2) Issuer:  has its DID service based on hyperledger 
3) Service provider has a DID based login implemented using BTC or any other chain (except EtherDID) 

**Q1: Now a QR code (SDR) is generated** by hyperledger based implementation, then will it be compatible to be processed by user DID application which is running on top of DAF implementation

**Q2: If above works out then**, when a HL based Issuer signs and share the attestations then will it be processed and saved in the same way like DAF based issuer?

**Q:3 - When a Service provider receives** a VP containing the VC's based on DAF, will it compatible to process it?

**Comment by mirceanis** [comment]
Theoretically yes for all questions; at least that is the goal.
Of the above questions, I think Q2 is closest to being true now.
It depends more on the types of keys and signatures used than on the blockchain they are anchored on.
These specific scenarios haven't been tested out so they probably don't work out of the box, but the purpose of DAF is to make this possible without caring which DID type or VC format is being used.

At this point in time, DAF is sure to support all the DID methods that are also supported by uniresolver.io and can handle Verifiable Credentials with the JWT encoding that are signed by secp256k1 or ed25519 keys.
In terms of issuance and control, it can deal with ethr-did, web-did (and elem-did as an experimental method)

We expect to grow the support to JSON and JSON-LD verifiable credentials along with various other proof formats, by creating new plugins that can interop with libraries in that space, but I can't make any promises on the timeline.
