### ISSUE TITLE
Why we need both kms and key manager in the beta?

### ISSUE THREAD

**Issue by thomas-tran** [uport-project/daf#256]
In the agent framework beta version, why we need both kms with keystore and the key manager with keystore?

**Comment by mirceanis** [comment]
A KMS is a specific implementation of an [AbstractKeyManagementSystem](https://github.com/uport-project/daf/blob/a50275b95d273399882aad4eba702b6169aea61d/packages/daf-key-manager/src/abstract-key-management-system.ts#L3). This could be a system that relies on mnemonic key derivation or one that wraps a WebKMS API, etc, to create and manage keys.

An agent can be configured with multiple of these systems simultaneously.

The [key manager](https://github.com/uport-project/daf/blob/a50275b95d273399882aad4eba702b6169aea61d/packages/daf-key-manager/src/key-manager.ts#L22) is a plugin that wraps multiple KMSs behind a group of methods that can be called directly by the client app or by other plugins to use the capabilities of the particular KMS that implements that capability.

An agent can have only one of these Key Manager plugins setup.

This particular way of doing things is possibly going to change in future releases, but the core principle that must remain is that multiple key providers must be usable in the same agent and they must be composable and interchangeable.
If some code is calling `agent.keyManagerSignJWT(...)` for example, they should be able to switch the key provider without changing that code.

I hope this answers your question.
I made some assumptions about which pieces of code you are referring to. Please reopen if I didn't hit the spot.
