### ISSUE TITLE
MessageHandler Unhandled error

### ISSUE THREAD

**Issue by simonas-notcat** [uport-project/daf#294]
**Bug severity**
5

**Describe the bug**
When calling `agent.handleMessage` with some random data I expect to get `Unsupported message type` error, but instead, I'm getting

```
UnhandledPromiseRejectionWarning: Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Unsupported message type')
    at EventEmitter.emit (events.js:199:17)
```

**To Reproduce**
Steps to reproduce the behaviour:
1. `daf msg --save false -r hello`

**Expected behaviour**
Should throw `Unsupported message type` error

**Versions:**
 - Daf: 7.0.0-beta.56
 - Node Version v12.13.1

**Comment by mirceanis** [comment]
fixed in #300
