### ISSUE TITLE
Provide mechanism and examples to use QR Code flows for issuance

### ISSUE THREAD

**Issue by awoie** [uport-project/daf#84]
We should provide examples and add missing functionality (e.g., message validators) for how to use QR Codes to issue and receive a VC.

Issuance flow:
- issuer creates VC and puts that VC into a `message` using DAF. The `message` contains a simple callback URL.
- holder scans the `message` (e.g., QR Code) and provides it to DAF for further processing.  The response is sent to the callback URL, e.g., approved / not approved. Sending the response is important in some cases to acknowledge that the holder received the VC.

**Comment by mirceanis** [comment]
relates to #83

**Comment by simonas-notcat** [comment]
@awoie this [example](https://github.com/uport-project/daf/tree/master/examples/expressjs-ethr) has everything except for callback URL. It is using serviceEndpoint in DIDDoc instead. Can we close this issue? We will implement something like callback URL when implementing JWM reply_url

**Comment by mirceanis** [comment]
> We will implement something like callback URL when implementing JWM reply_url
I think it is a good idea to separate these concepts.
Most likely not all messages will be JWM

**Comment by awoie** [comment]
that sounds good. will close this issue.
