### ISSUE TITLE
Provide mechanism and examples to use QR Code flows for SDR

### ISSUE THREAD

**Issue by awoie** [uport-project/daf#85]
We should provide examples and add missing functionality (e.g., message validators) for how to use QR Codes to create SDR and respond to a SDR.

SDR flow:
- verifier creates SDR `message` using DAF and specifies whitelisted issuers and VC types and or claims. The `message` contains a simple callback URL.
- holder scans the `message` (e.g., QR Code) and provides it to DAF for further processing to answer the SDR. The response is sent to the callback URL.

**Comment by mirceanis** [comment]
related to #83

**Comment by simonas-notcat** [comment]
@awoie this [example](https://github.com/uport-project/daf/tree/master/examples/expressjs-ethr) has everything except for callback URL. It is using serviceEndpoint in DIDDoc instead. Can we close this issue? We will implement something like callback URL when implementing JWM reply_url

**Comment by awoie** [comment]
that sounds good. i will close this issue.
